name: mini_widget
description: Flutter base component package, For example InkCell, BlocProvider, etc.
version: 1.0.0
homepage: https://github.com/flutterme/mini_widget.git

environment:
    sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  keyboard_actions: ^3.2.1
  material_design_icons_flutter: ^4.0.5045
  url_launcher: ^5.1.1
  cached_network_image: ^2.0.0-rc
  flutter_svg: ^0.18.1
  oktoast: ^2.2.0
  flutter_widget_from_html: ^0.3.1-rc
  permission_handler: ^5.0.1+1
  amap_location_fluttify: ^0.10.0+e74b91b
  flutter_spinkit: ^4.1.2+1
  qr_flutter: ^3.2.0
  webview_flutter: ^0.3.18+1
  flutter_swiper: ^1.1.6
  rxdart: ^0.24.0
  flutter_easyrefresh: ^2.1.0
  shimmer: ^1.1.1
  image_picker: ^0.6.5
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  mini_tools:
    git:
      url: https://github.com/collectFlutter/mini_tools.git
      ref: main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/empty_icon.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
