name: mini_widget
description: Flutter base component package, For example InkCell, BlocProvider, etc.
version: 3.0.0
repository:

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  easy_refresh: ^3.3.2+1
  fluro: ^2.0.5
  flutter_lints: ^2.0.0
  material_design_icons_flutter: ^7.0.7296
  oktoast: ^3.3.1
  shimmer: ^3.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

